### ISSUE TITLE
How  can i login successful?

### ISSUE THREAD

**Issue by LMM0709** [jberkel/android-market-api#1]
When i run Main.java with my google account there was an exception: 

com.gc.android.market.api.Tools$HttpException: HTTP Code 404 : https://developers.google.com/accounts/docs/AuthForInstalledApps
	at com.gc.android.market.api.Tools.postUrl(Tools.java:66)
	at com.gc.android.market.api.MarketSession.login(MarketSession.java:139)
	at com.gc.android.market.api.MarketSession.login(MarketSession.java:126)
	at com.gc.android.market.api.Main.main(Main.java:33)

**Comment by LunaticMeta** [comment]
i want to know that too
